/* Build the RhetorLint widget by inlining the REAL engine + rules + panel.
 * No hand-copying, so the widget can never drift from @rhetorlint/core.
 *
 *   node apps/widget/build.mjs
 *
 * Produces:  apps/widget/content.js      (the extension content script)
 *            apps/widget/bookmarklet.html (a zero-install, drag-to-bookmarks demo)
 */
import { readFileSync, writeFileSync } from "node:fs";

const here = new URL("./", import.meta.url);
const read = (p) => readFileSync(new URL(p, here), "utf8");

// 1. the engine, with its ES `export` keywords stripped so it inlines cleanly
const engine = read("../../packages/core/index.mjs").replace(/^export\s+/gm, "");
// 2. the rule pack as a literal
const rules = JSON.parse(read("../../packages/rules-en/rules.json"));
const rulesLiteral = "const RULES = " + JSON.stringify(rules) + ";";
// 3. the in-page panel UI
const panel = read("./src/panel.js");

const core = [engine, rulesLiteral, panel].join("\n\n");

// ── the extension content script: hotkey + toolbar-button message ──
const content = `/* GENERATED by apps/widget/build.mjs — edit src/panel.js or the engine, then rebuild. */
(function () {
  if (window.__rhetorlintLoaded) return;
  window.__rhetorlintLoaded = true;
  "use strict";

${core}

  // Alt+Shift+R on any page marks the current selection.
  document.addEventListener("keydown", function (e) {
    if (e.altKey && e.shiftKey && (e.key === "R" || e.key === "r")) capRun();
  });
  // The toolbar button (via the background worker) does the same.
  if (typeof chrome !== "undefined" && chrome.runtime && chrome.runtime.onMessage) {
    chrome.runtime.onMessage.addListener(function (msg) { if (msg === "rhetorlint-run") capRun(); });
  }
})();
`;
writeFileSync(new URL("./content.js", here), content);

// ── the bookmarklet: same code, run immediately, packed into a javascript: URL ──
const bookmarkletBody = `(function(){"use strict";\n${core}\ncapRun();})();`;
const href = "javascript:" + encodeURIComponent(bookmarkletBody);
const bookmarkletHtml = `<!doctype html><html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>RhetorLint bookmarklet</title>
<style>
  body{font:16px/1.6 system-ui,sans-serif;max-width:640px;margin:3rem auto;padding:0 1.2rem;
    background:#f4f2ec;color:#221f18}
  @media(prefers-color-scheme:dark){body{background:#14161a;color:#e9e3d4}}
  a.bm{display:inline-block;padding:.6rem 1.1rem;border:1px solid #b1442f;border-radius:8px;
    color:#b1442f;text-decoration:none;font-weight:700;margin:1rem 0}
  code{background:rgba(128,128,128,.15);padding:.1rem .3rem;border-radius:3px}
  .muted{opacity:.7;font-size:.9rem}
</style></head><body>
<h1>RhetorLint — the bookmarklet</h1>
<p>Drag this button to your bookmarks bar. Then, on any page, select some text and click it — RhetorLint marks the rhetorical tells, on-device.</p>
<p><a class="bm" href="${href.replace(/"/g, "&quot;")}">🖍️ Read the subtext</a></p>
<p class="muted">Nothing you select ever leaves the page. No install, no network, no account. Some sites with a strict Content-Security-Policy will block bookmarklets — use the extension there instead.</p>
<p class="muted">Generated by <code>apps/widget/build.mjs</code> from the real <code>@rhetorlint/core</code> engine.</p>
</body></html>`;
writeFileSync(new URL("./bookmarklet.html", here), bookmarkletHtml);

console.log("built content.js (" + content.length + " bytes) and bookmarklet.html (" + bookmarkletHtml.length + " bytes)");
